quarkus.qute.alt-expr-syntax=true

# Site Configuration
site.url=https://danielmendss.github.io

# Collections Configuration
site.collections.posts.layout=post
site.collections.posts.future=false
site.collections.posts.hidden=false

